development:
  adapter: postgresql
  encoding: unicode
  database: torre_dev
  pool: 5
  username: postgres
  password: postgres 
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: torre_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: torre_prod
  pool: 5
  username: postgres
  password: postgres
  host: localhost
